apiVersion: v1
kind: ConfigMap
metadata:
  name: uav-store-config
  namespace: {{ include "uav-store.namespace" . }}
data:
  DB_USER: {{ .Values.config.DB_USER | quote }}
  DB_SSL_MODE: {{ .Values.config.DB_SSL_MODE | quote }}
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  ENV: {{ .Values.config.ENV | quote }}

  USER_SERVICE_URL: {{ .Values.config.USER_SERVICE_URL | quote }}
  FILE_SERVICE_URL: {{ .Values.config.FILE_SERVICE_URL | quote }}
  PRODUCT_SERVICE_URL: {{ .Values.config.PRODUCT_SERVICE_URL | quote }}
  PRODUCT_SERVICE_GRPC_ADDRESS: {{ .Values.config.PRODUCT_SERVICE_GRPC_ADDRESS | quote }}
  ORDER_SERVICE_URL: {{ .Values.config.ORDER_SERVICE_URL | quote }}
  ORDER_SERVICE_GRPC_ADDRESS: {{ .Values.config.ORDER_SERVICE_GRPC_ADDRESS | quote }}
  PAYMENT_SERVICE_URL: {{ .Values.config.PAYMENT_SERVICE_URL | quote }}

  MINIO_ENDPOINT: {{ .Values.config.MINIO_ENDPOINT | quote }}
  MINIO_PUBLIC_ENDPOINT: {{ .Values.config.MINIO_PUBLIC_ENDPOINT | quote }}
  MINIO_USE_SSL: {{ .Values.config.MINIO_USE_SSL | quote }}
  MINIO_REGION: {{ .Values.config.MINIO_REGION | quote }}
  STORAGE_BUCKET_NAME: {{ .Values.config.STORAGE_BUCKET_NAME | quote }}

  API_GATEWAY_EXTERNAL_URL: {{ .Values.config.API_GATEWAY_EXTERNAL_URL | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.CORS_ALLOWED_ORIGINS | quote }}

  PAYOS_RETURN_URL: {{ .Values.config.PAYOS_RETURN_URL | quote }}
  PAYOS_CANCEL_URL: {{ .Values.config.PAYOS_CANCEL_URL | quote }}
