apiVersion: v1
kind: Secret
metadata:
  name: uav-store-secrets
  namespace: {{ include "uav-store.namespace" . }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}

  minio-root-user: {{ .Values.secrets.minioRootUser | quote }}
  minio-root-password: {{ .Values.secrets.minioRootPassword | quote }}

  user-db-password: {{ .Values.secrets.userDbPassword | quote }}
  product-db-password: {{ .Values.secrets.productDbPassword | quote }}
  order-db-password: {{ .Values.secrets.orderDbPassword | quote }}
  payment-db-password: {{ .Values.secrets.paymentDbPassword | quote }}

  payos-client-id: {{ .Values.secrets.payosClientId | quote }}
  payos-api-key: {{ .Values.secrets.payosApiKey | quote }}
  payos-checksum-key: {{ .Values.secrets.payosChecksumKey | quote }}
