apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s