apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  admin-user: {{ .Values.secrets.grafanaAdminUser | quote }}
  admin-password: {{ .Values.secrets.grafanaAdminPassword | quote }}
